header:
  version: 11
machine: qemuarm
distro: beskar
target:
  - whistling-bird
repos:
  meta-beskar:
    layers:
      meta-beskar:
  meta-clang:
    url: "https://github.com/kraj/meta-clang.git"
    branch: "walnascar"

  openembedded-core:
    url: "https://github.com/openembedded/openembedded-core.git"
    branch: "walnascar"
    layers:
      meta:
  bitbake:
    url: "https://github.com/openembedded/bitbake.git"
    branch: "2.12"
    layers:
      .: excluded
  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "walnascar"
    layers:
      meta-arm-toolchain:
      meta-arm:
local_conf_header:
  meta-beskar: |
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
    MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "kernel-modules"
