header:
  version: 11
machine: beaglebone
distro: beskar
target:
  - whistling-bird
repos:
  meta-beskar:
    layers:
      meta-beskar:

  openembedded-core:
    url: "https://github.com/openembedded/openembedded-core.git"
    branch: "walnascar"
    layers:
      meta:
  bitbake:
    url: "https://github.com/openembedded/bitbake.git"
    branch: "2.12"
    layers:
      .: excluded
  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "walnascar"
    layers:
      meta-arm-toolchain:
      meta-arm:
  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: master
    layers:
      meta-ti-bsp:
      meta-beagle:
local_conf_header:
  meta-kiss: |
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
